### ISSUE TITLE
Предложения по улучшению/баги

### ISSUE THREAD

**Issue by eugenevitah** [FriendsTRUST/trust-swap-frontend#2]
Оценивайте мой отзыв не как требование, но как желание сделать сервис более удобным и дружелюбным к пользователям.

1. Надпись: "Условия начисление кешбэка". На конце второго слова должна быть буква "я".
2. Необходимо усовершенствовать механизм сортировки/отображения токенов в окне выбора монет.
К примеру, если написать **TON**, то первым в списке будет **NEWTON**, почему бы не сделать так, чтобы список отображался, начиная со слова, которое было вписано в поле поиска, а дальше в алфавитном порядке?
Так же, при поиске **TON** появляется токен **DEADPOOL**, который не имеет отношения к **TON**, но в его описании есть совпадение с запросом - слово Winston. Мне кажется, так не должно быть.
Пересмотрите, пожалуйста, механизм поиска токенов, чтобы исключить описанные выше моменты.
3. В графике всё еще есть моменты, которые можно доработать.
Нужны бОльшие "волны", потому что в некоторых парах, если цена и разнится, то на графике это не сильно заметно издалека. Линия очень слабо отклоняется по вертикали.
Так же, я предлагаю опустить ось абсцисс до самого низа, ведь отрицательные значения совсем не нужны, правильно? В результате этого, на шкале будет вмещаться больше числовых шагов, а также появится больше места сверху.
Еще один момент я бы улучшил - верхние границы. Можно сделать самую верхнюю точку на графике намного ближе к верхней границе.
Например, график **TRUST/BIP** - на его шкале есть верхнее значение 0.8, но оно не используется, т.к. на недельном промежутке (1W) максимальным значением является 0.5579 (на момент написания этого отзыва).
Следующий момент - текущая стоимость (отображается на зеленом фоне справа от графика поверх шкалы). Возьму за пример пул **ETH/SQD**. Стоимость по количество высокая, т.е. видим длинное число, но в нём в добавок слишком много цифр после запятой. На больших значениях, можно было бы ограничить отображения цифр после запятой до 2 шт.
4. Для списка токенов нужно бОльшая высота окна, чтобы вмещалось больше токенов. Мое предложение - сделать так, чтобы список вмещал минимум 5 токенов.
Нижняя граница обрезает последнюю строку токена, иногда не видно даже его количества - прокрутка списка в таком случае, чтобы посмотреть количество, лишняя. Можно было бы решить этот момент таким образом, чтобы все монеты в списке вмещались полностью, т.е. 1 прокрутка списка показывала строку со следующим токеном полностью.
Так же предлагаю сделать высоту строк токенов фиксированной, чтобы каждая строка была одинакова по высоте; уменьшение верхних и нижних полей строчки тоже желательна, т.к. слишком много пустого места, но не сильно, буквально на 5-7 пикселей с обоих сторон. Например, вписав название **HUB** мы видим, что вторая строка **BUBBLEGUM** выше других строк за счет длинного описания, занимающего дополнительно 2 строчки.

**Comment by vyuldashev** [comment]
Здравствуйте, спасибо за предложения! Часть из них уже находится в бэклоге, часть возьмем на заметку.
